name: 'test_project'

version: '1.0.0'

config-version: 2

profile: 'test_project'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"

log-path: "logs"

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  test_project:  
    +materialized: view
    +schema: dev
  